### ISSUE TITLE
Missing field ‘algorithm’ at line 1 column 2

### ISSUE THREAD

**Issue by koehn** [mautrix/meta#108]
I started a new chat on FB and while the bridge created the room correctly (i.e., with the correct name), all of the messages look like this:

```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.bad.encrypted",
    "body": "** Unable to decrypt: DecryptionError: missing field `algorithm` at line 1 column 138 **"
  }
}
```

**Comment by tulir** [comment]
Missing event source, that field probably can't be missing anyway 🤔
