### ISSUE TITLE
Migration from old Python bridge

### ISSUE THREAD

**Issue by christheradioguy** [mautrix/meta#12]
Hello,

I am currently using the old Python bridge for FB Messenger bridging (https://github.com/mautrix/facebook) and am considering switching to this bridge in order to gain support for Messenger E2E Encrypted messages.  Wondering if it is possible to migrate chat history from the old bridge, or if I'll end up with orphaned rooms from the old bridge and new rooms for this one?

**Comment by maltee1** [comment]
There is no migration path (yet), but if you set up backfill correctly, chat history will be imported. You should have bridge bot and ghosts leave all rooms using `clean-rooms` before deleting the old bridge

**Comment by christheradioguy** [comment]
Thanks for the reply, I'll take a look at the backfill options.

Is there any plans to support migration from the older bridge in the future?
