### ISSUE TITLE
The bridge not working on https://business.facebook.com/

### ISSUE THREAD

**Issue by af913337456** [mautrix/meta#15]
Hello @tulir, thank you for your contribution.

My issue is according to the instructions, when I use the bridge, I use it in the `https://www.facebook.com/` It's normal. But in the `https://business.facebook.com/` When it was discovered that it could not be received `wss://edge-chat.facebook.com/chat...` Is this normal for socket messages?

**Comment by tulir** [comment]
The bridges are meant for personal use, so business accounts aren't supported unless they happen to work already
