### ISSUE TITLE
Intermittent "Unsupported message" sending link via Messenger web

### ISSUE THREAD

**Issue by psylenced** [mautrix/meta#16]
I sent the following (intentionally bad link) via messenger.com web to someone else.

The link was ```tiktok.com/random_video``` (no http or anything).

When viewing in beeper, I got an **Unsupported message** error.

```
Decrypted event source
{
  "room_id": "!xxxxxxxxxx:beeper.local",
  "type": "m.room.message",
  "content": {
    "body": "Unsupported message (*waArmadilloApplication.Armadillo_Content_ExtendedContentMessage)",
    "fi.mau.double_puppet_source": "mautrix-meta",
    "m.mentions": {},
    "msgtype": "m.notice",
    "_isEmojiBody": null
  }
}
```

I found reference to that property (Armadillo_Content_ExtendedContentMessage) in from-whatsapp code, but not in the meta code.

I tried multiple times to reproduce the error, but all worked as expected and came through with expected message type and preview.

Just posting bug in case it relates to missing functionality.

**Comment by tulir** [comment]
Some fancier message types aren't supported yet, so that's expected. Beeper issues should be reported via the in-app mechanism, not here.

**Comment by psylenced** [comment]
No problems. Bad assumption on my part that the error related to the bridge due to the code reference.

**Comment by tulir** [comment]
I meant all issues that happen on beeper should be reported to beeper even if they're related to bridges
