### ISSUE TITLE
Messenger voice messages (Element X)

### ISSUE THREAD

**Issue by UntriexTv** [mautrix/meta#17]
I used old messenger bridge, and now was forced to move to this one, because of encryption.

The behavior of messenger bridge was, that the received voice messages showed like playable message, same as when sending voice message, or in messenger app or IG app etc...

But the meta bridge receives file voice.mp3 and I am not able to play it back in the app.

**Comment by Virkkunen** [comment]
I think this might be an issue specifically with Element X, as I can play voice messages just fine with another client like FluffyChat, so maybe it's better to open an issue on [Element X's repo](https://github.com/element-hq/element-x-android)?

**Comment by tulir** [comment]
When reporting issues with events, event content is required.

**Comment by UntriexTv** [comment]
> I think this might be an issue specifically with Element X, as I can play voice messages just fine with another client like FluffyChat

I used element X with old messenger bridge too and it worked well (Showed play button, similar interface to messenger). But after update to meta it just receives it as file, At least if I understand it correctly.


> When reporting issues with events, event content is required.

Sorry, could you tell me where should I look for it? I tried logs for synapse and meta bridge but didn't find it.

**Comment by tulir** [comment]
View source in the message context menu

**Comment by UntriexTv** [comment]
It fixed the issue, but still acts weird compared to IG integration.

On element web everything works alright.
But on element (X and normal) there is no waveform and the play "pointer" doesn't move, or allow to skip forward.

**Comment by tulir** [comment]
Waveforms aren't required so that's probably a client bug
