### ISSUE TITLE
Every reboot results in room change (MyName changed their avatar)

### ISSUE THREAD

**Issue by UntriexTv** [mautrix/meta#18]
Basically the title. Before I updated today it showed two room updates every morning (my server restarts on midnight), Now after update and starting server it shows just one update.
Every time it is `My Name changed their avatar`. Chats fill up with room changes quickly this way.

Edit: It still happens two times after reboot.

**Comment by DoM1niC** [comment]
yep same Problem after reject or delete existing Rooms, the Bridge fill up after every restart

**Comment by MajliTech** [comment]
It's not a bug (i think), the bridge should show every chat avaiable.

**Comment by hafx** [comment]
Same issue (0.2.0).
I receive all the invites from rooms I rejected at every restart of the bridge. If I reject 1 time, why I need to reject at every restart ?
For no reason I have also the same problem without restarting the bridge every 2-3 days. 

Any idea ?

**Comment by immanuelfodor** [comment]
This is addressed in https://github.com/mautrix/meta/releases/tag/v0.3.2

**Comment by slagiewka** [comment]
Can confirm. I did couple of restarts since the update and don't see this issue anymore.
