### ISSUE TITLE
Failing to bridge to facebook messenger "Missing some cookies"

### ISSUE THREAD

**Issue by Aadniz** [mautrix/meta#2]
Following the steps here: https://docs.mau.fi/bridges/go/meta/authentication.html I cannot get this to work.

Pasting JSON of cookies (from [Cookie-Editor](https://addons.mozilla.org/en-US/firefox/addon/cookie-editor/) firefox extension) results in the bridge bot saying `Failed to parse input as JSON: json: cannot unmarshal array into Go value of type cookies.InstagramCookies`.

Copying the websocket request as cURL makes the bot say: `Missing some cookies` even though I can clearly see they are all there in the request. The instructions for copying this network info from chrome just tells you to copy, but there is no way to *just* copy. The copy as cURL in chrome doesn't include cookies.

I don't expect this issue to be specific to only me and my setup.

**Comment by tulir** [comment]
JSON cookies must be a simple key-value object, no arrays. Didn't realize copying websockets on chrome doesn't include cookies, I guess I'll switch the example to use a normal api request instead. Also made it say which cookies are missing now

**Comment by Aadniz** [comment]
Thank you for quick reply!
I now see the JSON message worked, and with the updated main branch, it shows this message:

```
Missing some cookies: [mid ig_did ds_user_id sessionid csrftoken]
```

My guess is that it really are looking for instagram cookies, but this is a facebook messenger bridge I'm setting up

**Comment by tulir** [comment]
Did you tell it that it's a facebook bridge?

**Comment by Aadniz** [comment]
That's it, It looks like that option got created by itself when I copied the old config from [mautrix/facebook](https://github.com/mautrix/facebook) earlier. Thank you for helping out
