### ISSUE TITLE
How to reload websocket connection when it's down?

### ISSUE THREAD

**Issue by AZSJTinus** [mautrix/meta#21]
Sometimes something goes wrong in the meta messenger bridge resulting in messages like the one below appearing in the "Messenger bridge bot" room:
`Error in WhatsApp connection: CAT refresh failed`

Afterwards, sending messages results in these messages appearing in the personal chat rooms:
`⚠ Your message may not have been bridged: failed to send message node: websocket not connected`

However I'm unable to reconnect to the websocket, there appears to be no 'refresh' command.
`Failed to parse input as JSON: invalid character 'r' looking for beginning of value`

Only logging out and in again appears to fix the issue, however this is not really feasible as there is no easy way to get the cookies on mobile.

Is there an other possibility to reconnect?

**Comment by tulir** [comment]
That was already fixed in the latest version. Logs are also required for almost any issues

**Comment by AZSJTinus** [comment]
It appears to not be fixed as I'm on version 0.1.0 since at least 26/feb and received the same messages today:
![image](https://github.com/mautrix/meta/assets/161581636/27f476ce-4fce-498a-bb4e-35cf9030b2d9)

Version 0.1.0:
![image](https://github.com/mautrix/meta/assets/161581636/38a1bc7a-2703-4bf9-b51b-0ce28aed0cba)

**Comment by tulir** [comment]
Releases are almost always outdated

**Comment by Devenda** [comment]
Ok thanks for the info, than I'll wait for the new release.

**Comment by kevincox** [comment]
I've hit this as well. It would be great to have a command to do this. Reloading the bridge seems to work but I don't always have a terminal easily available. Even just a shutdown command would be great, then the service manager can reload.
