### ISSUE TITLE
Multi-account support

### ISSUE THREAD

**Issue by kubo6472** [mautrix/meta#3]
I know this was already dismissed as not planned/low priority, but I'd still love for this to be runable as a single bridge either creating two admin rooms, or One room with commands like login-fb and login-ig.

There was also some talk that encryption might be powered by whatsmeow and WhatsApp might be a part of this bridge's code. I doubt that's in any short term plans, though.

**Comment by maltee1** [comment]
I suppose there are two ways to think about this:
1. A single user can log in with *both* IG and FB on the same bridge
2. A single user can log in with *either* IG or FB on the same bridge. If federation between IG and FB happens, this could give us shared group chat portals.
