### ISSUE TITLE
The bridge fails to start because some table in Synapse DB does not exist

### ISSUE THREAD

**Issue by vojtapolasek** [mautrix/meta#30]
I think the upgrade routine fails.
This repeats many times in the log of my Postgres container:

synapse-db-1  | 2024-03-06 17:30:20.942 UTC [40] ERROR:  relation "events_room_stream2" does not exist
synapse-db-1  | 2024-03-06 17:30:20.942 UTC [40] STATEMENT:  ALTER INDEX events_room_stream2 RENAME TO events_room_stream

Any solution?

I am replacing mautrix-facebook with mautrix-meta. If you need more info just let me know. Thank you.

**Comment by tulir** [comment]
The Synapse database isn't related to the bridge in any way
