### ISSUE TITLE
When user tweaks permissions, make sure to warn the user about possible consenquences.

### ISSUE THREAD

**Issue by MajliTech** [mautrix/meta#38]
Hello!
I manage a Meta bridge for Messenger. I recently expermineted so some users could hook into the chat for read-only. When tweaking the `Send messages` permission, turns out (as it should) this affected the puppeting bridges. In the future (if this is even detecteable) the bridge should send a warning  about possible messeages not arriving properly.

Regards.

**Comment by MajliTech** [comment]
If I make a pull request for this, will it be possibly implemented?

**Comment by tulir** [comment]
Probably not, seems completely unnecessary
