### ISSUE TITLE
bug(instagram): replies from IG don't show on mobile

### ISSUE THREAD

**Issue by phorcys420** [mautrix/meta#39]
The incoming replies (from IG) don't display properly on mobile ([Element Desktop](https://github.com/mautrix/meta/assets/57866459/57c7fd6b-6444-473d-a35e-ef4201e08d49) vs [Element Mobile](https://github.com/mautrix/meta/assets/57866459/7f10de19-2a45-4357-a41b-e291cc59a045)).

While this misinterpretation might be related to a bug on Element Mobile, this does not happen with the other Mautrix bridges (namely Signal and Telegram).
As you can see with the following snippets, the raw contents of an incoming message differ quite a lot beteen the Telegram bridge and the IG bridge, I believe this could be the cause of the issue.

<details>
  <summary>
  Source of an incoming message (mautrix-meta Instagram)
  </summary>

  ```json
  {
    "room_id": "![...]:[...]",
    "type": "m.room.message",
    "content": {
      "body": "reply from IG",
      "m.mentions": {
        "user_ids": [
          "@phorcys:[...]"
        ]
      },
      "m.relates_to": {
        "m.in_reply_to": {
          "event_id": "[...]"
        }
      },
      "msgtype": "m.text"
    }
  }
  ```
</details>

<details>
  <summary>
  Source of an incoming message (mautrix-telegram)
  </summary>

  ```json
  {
    "room_id": "![...]:[...]",
    "type": "m.room.message",
    "content": {
      "msgtype": "m.text",
      "body": "> <User (TG)> original message\n\nreply",
      "m.relates_to": {
        "m.in_reply_to": {
          "event_id": "[...]"
        }
      },
      "format": "org.matrix.custom.html",
      "formatted_body": "<mx-reply><blockquote><a href='https://matrix.to/#/![...]:[...]/[...]'>In reply to</a> <a href='https://matrix.to/#/@telegram_[...]:[...]'>User (TG)</a><br/>original message</blockquote></mx-reply>reply",
      "fi.mau.telegram.source": {
        "space": [...],
        "chat_id": [...],
        "peer_type": "user",
        "id": [...]
      }
    }
  }
  ```
</details>

**Comment by tulir** [comment]
Element Android never supported rendering replies correctly. Reply fallbacks are deprecated so they won't be added to new bridges anymore (and will eventually be removed in old bridges too)

**Comment by phorcys420** [comment]
Alright, thanks for the heads up.

**Comment by p1gp1g** [comment]
Does anyone knows if there is an issue related to this on element android repo ?
