### ISSUE TITLE
Alternative to WebUI login

### ISSUE THREAD

**Issue by kubo6472** [mautrix/meta#4]
I'd love to see an improvement/alternative in the current authentication.

One mentioned way was using some kind of electron app using Facebook's API.

**Comment by tulir** [comment]
The only way is the website, Electron is just a way to automate collecting cookies after logging in. Technically a [browser extension](https://github.com/tulir/mautrix-cookiemonster) could do that too, but to be safe it'd also need to clear cookies afterwards.

Anyway, electron apps and browser extensions are out of scope for the bridge and should live in separate repos

**Comment by kubo6472** [comment]
What I understood from your message two days ago in meta maunium matrix room is that a WebUI like mautrix-facebook is not planned, like at all.
