### ISSUE TITLE
Messenger not working with Facebook's new encryption stuff.

### ISSUE THREAD

**Issue by mijofa** [mautrix/meta#45]
I just switched to this bridge from mautrix-facebook the other day because messages were failing to send with a "Please update your app" response from Facebook, and things worked mostly fine for a couple of days.

Now Facebook forced my hand with enabling their chat history encryption stuff, and now all chats that have the encryption stuff enabled have stopped working with the bridge.
Trying to send a message results in a reply saying "⚠ Your message may not have been bridged: server rejected message: Couldn't send.", and messages sent to me simply don't appear in the bridge.

I knew enabling the encryption was likely to cause problems, but Facebook wouldn't let me look at messages in the web UI or mobile app without enabling it.
Since some messages were coming through the bridge a little bit wrong (shared reels/posts just showed a screenshot and no link) I had to check them in Facebook to get the whole message. :(

**Comment by tulir** [comment]
Automatically detecting when a chat switches to encrypted was implemented yesterday, but if you're using an old version of the bridge, the bridge will notice the chat is encrypted as soon as you receive an encrypted message. There's also `!fb toggle-encryption` to tell the bridge to send encrypted messages

**Comment by mijofa** [comment]
Ah ok, I'm using the latest release version via docker (`FROM dock.mau.dev/mautrix/meta:v0.2.0`) so won't quite have yesterday's changes yet.
I've just restarted the container and it's doing a whole bunch of backfill with some weirdly old chats now, seems to be doing so accurately. Looks like all the chats that switched to encrypted went to the top of the list, so now it's backfilled all those ones.

Doing `!fb toggle-encryption` in that particular room worked, thanks. :)
