### ISSUE TITLE
Enable logging into a Messenger only account

### ISSUE THREAD

**Issue by ppdms** [mautrix/meta#47]
In the EU we can have Messenger accounts without a Facebook profile (https://www.facebook.com/help/messenger-app/117818065545664), I tried logging into Messenger through Facebook in the webview and it recognized that I had a Messenger-only account and redirected me to another log-in page for Messenger credentials, but entering my correct login info doesn't do anything.

**Comment by tulir** [comment]
https://github.com/mautrix/meta/blob/main/example-config.yaml#L81-L86
