### ISSUE TITLE
Feature request: The ability to prevent certain portals from being created

### ISSUE THREAD

**Issue by prurigro** [mautrix/meta#55]
Hey, first I wanted to say thank you for all the work you've done turning matrix into a multi-protocol system :)

The main reason for requesting this feature is that there are about 36 portals getting opened when mautrix-meta is started. I'm aware of your position here https://github.com/mautrix/meta/issues/36 - but a good chunk of the portals that are getting opened are for people I've never talked to and who aren't in my friends list. Some of those people had sent a friend request at one point (probably bots), but others I've never heard of, including a user named "Unknown user". If I block the associated matrix account and close the chat, it re-opens the next time mautrix-meta is started.

I'm not necessarily looking for a way to avoid having portals getting opened in the first place (though only opening when a message is sent seems like it would fix this issue), but is there a way to at least tell mautrix-meta that I want to close a particular portal and not have it re-open?

Thanks!

**Comment by tulir** [comment]
You can delete chats on the native messenger apps or via the bridge using some command (should be listed in help)
