### ISSUE TITLE
Can not receive new message from Meta-Messenger

### ISSUE THREAD

**Issue by af913337456** [mautrix/meta#8]
Can not receive new message from Meta-Messenger.

1. Login facebook, open the messenger web page in facebook;
2. Copy the cookies and login this application;
3. Watching the log output.

when new message comming in messenger, the app can't receive it.

<img width="1066" alt="图片" src="https://github.com/mautrix/meta/assets/10436277/4a3b6f01-1f43-444d-b969-ede189ff8859">

<img width="1054" alt="图片" src="https://github.com/mautrix/meta/assets/10436277/20764360-0a79-40d3-8a89-ce9f2b319b9b">

**Comment by af913337456** [comment]
@tulir Hi, please help me.

**Comment by af913337456** [comment]
@tulir any suggestions？

**Comment by tulir** [comment]
That `user_id` field in the logs is suspicious, did you modify the bridge somehow?

**Comment by af913337456** [comment]
> That `user_id` field in the logs is suspicious, did you modify the bridge somehow?

I didn't make any changes. I used the login interface in Provisioning.go, and I noticed that it includes the user interface_ The ID reading is obtained from the URL query parameter, which can be specified directly. I then specified and called the login interface.

**Comment by tulir** [comment]
The user ID parameter must be a mxid. You also can't log into the same meta account with multiple matrix users.
