### ISSUE TITLE
Support PIN in new E2EE mode

### ISSUE THREAD

**Issue by blacklight** [mautrix/meta#83]
As of this week, Meta has apparently rolled out E2EE to Messenger.

It seems to support either on-device keys (messages are only accessible to the device where they're received), Google auth keys (only accessible to Android devices), or a PIN (accessible to all devices with the PIN).

Since the rollout of the feature, I'm no longer able to receive new messages on fb.

Is there already a plan to support at least PIN authentication to decrypt E2E messages?

**Comment by tulir** [comment]
Receiving new messages doesn't require a pin

**Comment by tulir** [comment]
Old messages are not the same as new messages. Backfill is not supported, new messages work fine.

If a new message is broken on official clients too, then there's probably something wrong on the sending side
