### ISSUE TITLE
Unexpected mis-escaping of URL

### ISSUE THREAD

**Issue by jtagcat** [mautrix/meta#88]
Element Web user sent link: `https://kultuurikatel.ee/virtuaaltuur/images/svg_2.svg`
Meta received: `https://kultuurikatel.ee/virtuaaltuur/images/svg\_2.svg`
Opened in browser as `https://kultuurikatel.ee/virtuaaltuur/images/svg/_2.svg`

**Comment by tulir** [comment]
The bridge doesn't do any escaping, it doesn't even support formatting yet
