### ISSUE TITLE
It seems that the function of replying to messages to the messenger is missing

### ISSUE THREAD

**Issue by af913337456** [mautrix/meta#9]
Hi @tulir good day , I checked the code and found that `portal.matrixMessages` seems not in use which means the bridge has not yet implemented sending messages to the messenger or meta, has it? thanks for your watching.

```go
func (portal *Portal) ReceiveMatrixEvent(user bridge.User, evt *event.Event) {
	if user.GetPermissionLevel() >= bridgeconfig.PermissionLevelUser || portal.HasRelaybot() {
		portal.matrixMessages <- portalMatrixMessage{user: user.(*User), evt: evt}
	}
}
```

**Comment by tulir** [comment]
Sending messages is of course supported. The list of features can be found in https://github.com/mautrix/meta/blob/main/ROADMAP.md
