### ISSUE TITLE
Can't login to instagram with latest version

### ISSUE THREAD

**Issue by surakin** [mautrix/meta#97]
I'm getting this message
`Login failed: Missing cookies: [sessionid csrftoken ds_user_id mid ig_did]`

But I clearly see the cookies in the cURL request :thinking: 
`-H 'cookie: mid=xxx; ig_did=xxx; csrftoken=xxx; ds_user_id=xxx; sessionid=xxx; wd=xxx; datr=xxx; shbid=xxx; shbts=xxx; rur=xxx' \`

Any ideas?

**Comment by fir3drag0n** [comment]
same problem here
