### ISSUE TITLE
Profile picture is reset multiple times in group chats

### ISSUE THREAD

**Issue by eyJhb** [mautrix/meta#99]
Starting a new issue, since the old one was closed here #67 .

This seems to still be happening running v0.3.2, however, it seems to only be happening for my own puppeteer account (ie. the one impersonating me).

![image](https://github.com/user-attachments/assets/999bb088-045b-47c8-864a-d4cdae2f0bcb)

**Comment by tulir** [comment]
Old versions are not supported
